# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - USE_SCRUTINIZER="no"

matrix:
  include:
    - php: 5.6
      env: PHPUNIT_FLAGS="--coverage-clover=coverage.clover" USE_SCRUTINIZER="yes"
    - php: 7.0
    - php: 7.1
  allow_failures:
    - php: 7.1

before_script:
  # Make sure all dev dependencies are installed
  - composer install

script:
  - vendor/bin/phpunit --configuration phpunit.travisci.xml $PHPUNIT_FLAGS
  - if [ "$USE_SCRUTINIZER" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [ "$USE_SCRUTINIZER" == "yes" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
