# Forces new Travis-CI Infrastructure
sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  # Make sure all dev dependencies are installed
  - composer install

script:
  - vendor/bin/phpunit --configuration phpunit.travisci.xml
